#!/bin/bash

#extract services from VL
if [ $1 = "1" ]; then
	cat routes.txt | awk 'BEGIN { FS=",";}; { if ( ($2 ==266) && ($6 == 3) ){print $0 } };' > VL
fi

#extract track 6 from VL
if [ $1 = "2" ]; then
	cat VL | awk 'BEGIN {FS=",";} { if ( ($3 == 6) ){ print $0 } }' > 266_6_BLT/VL_L6
fi