#!/bin/bash

trackNumber="4"
compareString="266_"$trackNumber"_BLT"

# compareString=${compareString}
if [ $1 = "1" ]; then

	declare -a myArray	
	echo "for safety, removing files that will be used"
	rm 266_${trackNumber}_BLT_service_id
	rm 266_${trackNumber}_BLT_stop_times_truncated.txt
	echo "--------------------------------------------"
	
	cat ../trips.txt | awk -v trackNumber=${trackNumber} -v awkCompareString="$compareString" 'BEGIN {FS=",";} { if ( $1 == awkCompareString ) {print $0} }' > 266_${trackNumber}_BLT_trips	
	cat 266_${trackNumber}_BLT_trips | awk '
		BEGIN {FS=","} 
		{ uniqueValues[$2] = $2 } 
		END { for (i in uniqueValues) {print uniqueValues[i] } }'  >> 266_${trackNumber}_BLT_service_id
	mkdir parsed
	
	lastIndex=`wc -l 266_${trackNumber}_BLT_trips | awk '{print $1}'`	
	cat 266_${trackNumber}_BLT_trips | awk -F"," -v lastIndex=$lastIndex 'BEGIN {ORS="\n"}; {if (NR==1) {print $3}}; {if (NR==(lastIndex)) {print $3}}' >> firstAndLastTrip				
	i=0
	while IFS=$'\n' read -r line_data; do
    	myArray[i]="${line_data}"
    	((++i))
	done < firstAndLastTrip
	rm firstAndLastTrip

	cat "../stop_times.txt" | awk -F"," -v firstTrip=${myArray[0]} -v lastTrip=${myArray[1]} '{if ( ($1==firstTrip) || ($1==lastTrip) ) {print NR}}' >> lineIndexes
	i=0
	while IFS=$'\n' read -r line_data; do
    	myArray[i]="${line_data}"
    	lastindex=$i
    	((++i))    	
	done < lineIndexes
	rm lineIndexes

	cat "../stop_times.txt" | awk -F"," -v lowerIndex=${myArray[0]} -v upperIndex=${myArray[$lastindex]} '{if ((NR>lowerIndex) && (NR<upperIndex)) {print $0}}' >> 266_${trackNumber}_BLT_stop_times_truncated.txt
	echo "finished trimming ../stop_times.txt"	

fi

if [ $1 = "2" ]; then

	echo "removing whitespace from 266_"${trackNumber}"_BLT_trips_withoutblankspace"
	cat '266_'${trackNumber}'_BLT_trips' | awk 'BEGIN {FS=",";} { print $0 }' | tr -d '[:blank:]' >> '266_'${trackNumber}'_BLT_trips_withoutblankspace'
	mv '266_'${trackNumber}'_BLT_trips_withoutblankspace' '266_'${trackNumber}'_BLT_trips'
	echo "---------"

	echo "get route_ids for each service_id and move them to parsed folder"
	arrayServiceId=$"`cat 266_${trackNumber}_BLT_service_id`"	
	for item in $arrayServiceId; do
		rm "parsed/266_${trackNumber}_BLT_trips_${item}"
		touch "parsed/266_${trackNumber}_BLT_trips_${item}"
		cat 266_${trackNumber}_BLT_trips | awk -v trip_id=$item '
			BEGIN {FS=",";} 
			{ if ($2 == trip_id ) 
				{ print $0 }
			} ' >> "parsed/266_${trackNumber}_BLT_trips_${item}"
	done
	echo "---------"

	echo "collecting trips for each route_id and service_id, moving them to parse/266_${trackNumber}_BLT_trips_stops_service_id_#"
	for item in $arrayServiceId; do
		rm "parsed/266_${trackNumber}_BLT_trips_stops_service_id_${item}"
		touch "parsed/266_${trackNumber}_BLT_trips_stops_service_id_${item}"	

		routeId=(`cat parsed/266_${trackNumber}_BLT_trips_${item} | awk 'BEGIN {FS=",";} {print $1}'`)
		serviceId=(`cat parsed/266_${trackNumber}_BLT_trips_${item} | awk 'BEGIN {FS=",";} {print $2}'`)
		tripId=(`cat parsed/266_${trackNumber}_BLT_trips_${item} | awk 'BEGIN {FS=",";} {print $3}'`)
		full=(`cat parsed/266_${trackNumber}_BLT_trips_${item} | awk 'BEGIN {FS=",";} {print $0}'`)	
		
		for ((i=0; i<${#full[@]}; ++i)); do
			echo ${full[$i]} >> "parsed/266_${trackNumber}_BLT_trips_stops_service_id_${item}"	
			route_id=${routeId[$i]}
			trip_id=${tripId[$i]}
			service_id=${serviceId[$i]}
			cat 266_${trackNumber}_BLT_stop_times_truncated.txt | awk -v trip_id=$trip_id -v service_id=$service_id -v route_id=$route_id 'BEGIN {FS=",";} { if ($1 == trip_id )  {print route_id "," service_id "," $0} }' >> "parsed/266_${trackNumber}_BLT_trips_stops_service_id_${item}"
		done		
	done
	echo "---------"
fi

# OBS you may have to update row 157 if endstations have changed
if [ $1 = "3" ]; then

	echo "clean folder from old data"
	rm dumpPy/266_${trackNumber}_BLT_service_id_matchtimes
	rm dumpPy/266_${trackNumber}_BLT_service_id_with_dates
	echo "---------"

	arrayServiceId=$"`cat 266_${trackNumber}_BLT_service_id`"
	for item in $arrayServiceId; do
		rm "parsed/266_${trackNumber}_BLT_trips_stops_service_id_${item}_trunced"
		cat "parsed/266_${trackNumber}_BLT_trips_stops_service_id_${item}" | awk -v item=$item 'BEGIN {FS=",";} 
		{ if ( ($2 == item) )
			{ if ( ($4 != "Brottberga") && ($4 != "NorraMalmaberg") && ($4 != "Finnslättennorra")) 
				{ print $1","$2","$3","$4","$5",6"$6","$7",,,,"}
					else 
				{ print " "}
			}	
		}' >> "parsed/266_${trackNumber}_BLT_trips_stops_service_id_${item}_trunced"
	done
	
	for item in $arrayServiceId; do
		python ../python_code/makeTableEntry.py "parsed/266_${trackNumber}_BLT_trips_stops_service_id_${item}_trunced" "${item}" "${trackNumber}" 		
	done

	arrayServiceId=$"`cat 266_${trackNumber}_BLT_service_id`"
	for item in $arrayServiceId; do
		echo $item >> dumpPy/266_${trackNumber}_BLT_service_id_matchtimes
		python ../python_code/findLastAndFirst.py "parsed/266_${trackNumber}_BLT_trips_stops_service_id_${item}_trunced" "${item}" "${trackNumber}"		
	done
	echo "get dates when service_id is used"
	
	arrayOneAndTwo=$"`cat one.txt`"
	for item in $arrayOneAndTwo
		do
			one=$item
		done
		echo $one
	for item in $arrayServiceId 
		do 
			echo $item >> dumpPy/266_${trackNumber}_BLT_service_id_with_dates
			string=`awk -v item=$item '
			BEGIN {FS=","} 
			{ 
				if ( ($1 == item) ){
					print $0
				}
			} 
			' ../calendar.txt`
			python ../python_code/convert_calenderTxt.py $item $string >> dumpPy/calendar_dates_$item
			cat dumpPy/calendar_dates_$item >> dumpPy/266_${trackNumber}_BLT_service_id_with_dates
			# reading a variable like this makes awk understand what it is...
			cat ../calendar_dates.txt | awk -v item=$item '
			BEGIN {FS=","} 
			{ 
				if ( ($1 == item) ){
					print $3$2
				}
			} 
			' >> dumpPy/266_${trackNumber}_BLT_service_id_with_dates
			rm dumpPy/calendar_dates_$item
		done		

	python ../python_code/mapServiceIDtoDate.py ${trackNumber}

	# fix hardcoded JSON for webpage

	# python ../python_code/timeAndDates.py ${trackNumber}

fi

# Manually create 266_1_BLT_stationIDs
if [ $1 = "10" ]; then
	arrayStationsID=$"`cat realIDs`"
	rm 266_${trackNumber}_BLT_stationNames
	touch 266_${trackNumber}_BLT_stationNames
	for item in $arrayStationsID; do
		cat ../stops.txt | awk -v stationId=$item '
			BEGIN {FS=",";} 
			{ if ($1 == stationId ) 
				{ print $2 }
			} ' >> "266_${trackNumber}_BLT_stationNames"
	done
fi

if [ $1 = "push" ]; then
	arrayServiceId=$"`cat 266_${trackNumber}_BLT_service_id`"
	for item in $arrayServiceId; do
		python ../python_code/makeTableEntry.py "parsed/266_${trackNumber}_BLT_trips_stops_service_id_${item}_trunced" "${item}" "${trackNumber}" 		
	done
fi
